# Intro to numpy


In [82]:
# Dimensions in arrays
# 0D array-scalar- one numerical value
# 1D array-vector- list of elements
# 2D array-list of elements are the elements
# 3D array- 2D arrays are the elements

In [83]:
# arrays from lists or tuples
# np.array()

import numpy as np

my_list=[1,2,3,4,5]
arr1=np.array(my_list)
arr1

array([1, 2, 3, 4, 5])

In [84]:
my_list=[[1,2,3],[4,5,6]]
arr2=np.array(my_list)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
# array from random values

arr3=np.random.rand(5,5)
arr3

array([[0.90652144, 0.65414694, 0.49185588, 0.24877912, 0.96435884],
       [0.35147492, 0.30322857, 0.16234533, 0.70061095, 0.7245148 ],
       [0.69233135, 0.80769513, 0.02640388, 0.32331293, 0.50898074],
       [0.5410382 , 0.63058654, 0.57002769, 0.14503992, 0.20672668],
       [0.63788891, 0.19618495, 0.41342043, 0.66864664, 0.41715447]])

In [86]:
arr4=np.random.randint(100, size=(5,5))
print(arr4)

[[ 6 47  9 79 62]
 [21  3 79 68 37]
 [83 17  0 75 10]
 [ 1 19 32 17 39]
 [54 31 80 81 95]]


In [87]:
arr5=np.full((2,3,4),9)
print(arr5)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]


In [88]:
arr6=np.arange(0,50,2)
arr6

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [89]:
# temperature qtn
# create array to store temps for 5 days and 7 stations
arr7=np.random.randint(15,40, size=(5,7))
arr7

array([[31, 35, 27, 15, 24, 33, 23],
       [30, 32, 39, 30, 26, 27, 27],
       [15, 17, 23, 25, 33, 32, 38],
       [34, 26, 33, 39, 36, 25, 16],
       [33, 29, 34, 37, 28, 18, 34]], dtype=int32)

In [90]:
# initialize an array for 30 students starting at 25
arr8=np.random.randint(25,100, size=(30))
arr8

array([91, 92, 77, 52, 69, 25, 74, 84, 35, 66, 46, 97, 65, 58, 39, 48, 25,
       47, 89, 56, 87, 84, 33, 92, 40, 43, 69, 62, 89, 62], dtype=int32)

In [91]:
# 1. Array Attributes
# 2. Slicing and Indexing
# 3. Vecorization
# 4. Broeadcasting


In [92]:
# Array Attributes

import numpy as np

x1= np.random.randint(50, size=(3,5)).reshape(15,1)
x1

array([[14],
       [22],
       [37],
       [35],
       [47],
       [36],
       [33],
       [11],
       [ 4],
       [23],
       [12],
       [18],
       [32],
       [ 5],
       [39]], dtype=int32)

In [93]:
x1.reshape(5,3)

array([[14, 22, 37],
       [35, 47, 36],
       [33, 11,  4],
       [23, 12, 18],
       [32,  5, 39]], dtype=int32)

In [94]:
print(x1.shape)
print(x1.ndim)
print(x1.dtype)
x1.size

(15, 1)
2
int32


15

In [95]:
# Slicing and Indexing
# Accessing elements in an array

In [96]:
x2=np.arange(10,20,2)
x2

array([10, 12, 14, 16, 18])

In [97]:
print(x2[3])

16


In [98]:
x3=np.arange(10,100,3).reshape(5,6)
x3

array([[10, 13, 16, 19, 22, 25],
       [28, 31, 34, 37, 40, 43],
       [46, 49, 52, 55, 58, 61],
       [64, 67, 70, 73, 76, 79],
       [82, 85, 88, 91, 94, 97]])

In [99]:
# accessing 55
x3[2,3]

np.int64(55)

In [100]:
x4=x3.reshape(2,3,5)
x4

array([[[10, 13, 16, 19, 22],
        [25, 28, 31, 34, 37],
        [40, 43, 46, 49, 52]],

       [[55, 58, 61, 64, 67],
        [70, 73, 76, 79, 82],
        [85, 88, 91, 94, 97]]])

In [101]:
# accessing 76
x4[1,1,2]=100
x4

array([[[ 10,  13,  16,  19,  22],
        [ 25,  28,  31,  34,  37],
        [ 40,  43,  46,  49,  52]],

       [[ 55,  58,  61,  64,  67],
        [ 70,  73, 100,  79,  82],
        [ 85,  88,  91,  94,  97]]])

## Slicing arrays


In [102]:
x5=np.arange(10)
x5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
x5[4:7]

array([4, 5, 6])

In [104]:
x6=np.array([23,56,78,90,67])
x6

array([23, 56, 78, 90, 67])

In [105]:
x6[3:5]

array([90, 67])

In [106]:
x6[0:5:2]

array([23, 78, 67])

In [107]:
x7=np.array([23,56,78,90,67,50,45,89,34,10,29,44]).reshape(2,3,2)
x7

array([[[23, 56],
        [78, 90],
        [67, 50]],

       [[45, 89],
        [34, 10],
        [29, 44]]])

In [108]:
x7[:,:,1]

array([[56, 90, 50],
       [89, 10, 44]])

In [109]:
x7[1:3,1]

array([[34, 10]])

In [110]:
x7[0:3,2]

array([[67, 50],
       [29, 44]])

In [111]:
x7[0:2,1:3]

array([[[78, 90],
        [67, 50]],

       [[34, 10],
        [29, 44]]])

In [112]:
x8=np.array([0,1,2,3,4,5,6,7,8,9])
x8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
x8[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [114]:
a='BOB'
b=a[::-1]
if a==b:
    print("This is a palindrome")
else:
    print("Not a palindrome")

This is a palindrome


In [115]:
x4

array([[[ 10,  13,  16,  19,  22],
        [ 25,  28,  31,  34,  37],
        [ 40,  43,  46,  49,  52]],

       [[ 55,  58,  61,  64,  67],
        [ 70,  73, 100,  79,  82],
        [ 85,  88,  91,  94,  97]]])

In [117]:
x7

array([[[23, 56],
        [78, 90],
        [67, 50]],

       [[45, 89],
        [34, 10],
        [29, 44]]])

In [118]:
np.add(x7, 5)

array([[[28, 61],
        [83, 95],
        [72, 55]],

       [[50, 94],
        [39, 15],
        [34, 49]]])

In [119]:
np.multiply(x7, 2)

array([[[ 46, 112],
        [156, 180],
        [134, 100]],

       [[ 90, 178],
        [ 68,  20],
        [ 58,  88]]])

In [120]:
np.power(x7, 2)

array([[[ 529, 3136],
        [6084, 8100],
        [4489, 2500]],

       [[2025, 7921],
        [1156,  100],
        [ 841, 1936]]])

In [121]:
np.sqrt(x7)

array([[[4.79583152, 7.48331477],
        [8.83176087, 9.48683298],
        [8.18535277, 7.07106781]],

       [[6.70820393, 9.43398113],
        [5.83095189, 3.16227766],
        [5.38516481, 6.63324958]]])

In [122]:
x9=np.random.rand(20)
x9

array([0.0131176 , 0.14291129, 0.08317473, 0.64413265, 0.44728788,
       0.48108834, 0.19267175, 0.59937263, 0.54902238, 0.74841276,
       0.62051344, 0.24373225, 0.19603335, 0.89187234, 0.99190845,
       0.46833894, 0.92043198, 0.58557411, 0.17376398, 0.56799492])

In [123]:
np.cos(x9)

array([0.99991397, 0.98980555, 0.99654298, 0.79962091, 0.90162347,
       0.88649183, 0.98149615, 0.82568969, 0.8530351 , 0.73276987,
       0.81358002, 0.97044405, 0.98084692, 0.62795598, 0.54709335,
       0.89231933, 0.60547642, 0.83339492, 0.98494099, 0.84298129])

In [ ]:
# AGGREGATION
# rows axis=0
# columns axis=1
x10=x7.reshape(3,4)
x10

array([[23, 56, 78, 90],
       [67, 50, 45, 89],
       [34, 10, 29, 44]])

In [133]:
x10=x7.reshape(3,4)
x10

np.sum(x10, axis=0)

array([124, 116, 152, 223])

In [ ]:
# BROADCASTING
# rules:
# numpy checks trailing dimension should  equal or one of them one
# do the same for first dimension
# 
ar1=np.arange(5)
ar2=np.array([1,2,3,4,5])
np.add(ar1,ar2)

array([1, 3, 5, 7, 9])

In [1]:
# MASKS COMPARISONS AND BOOLEAN OPERATORS IN NUMPY
import numpy as np

weights=np.array([52,43,67,55,45,28,64])
weights

array([52, 43, 67, 55, 45, 28, 64])

In [2]:
obese_mask=weights>60
obese_mask

array([False, False,  True, False, False, False,  True])

In [3]:
obese_patients=weights[obese_mask]
obese_patients

array([67, 64])

In [4]:
moderate_mask=(weights>=40)&(weights<=60)
moderate_mask

array([ True,  True, False,  True,  True, False, False])

In [5]:
not_obese_mask=weights<60
not_obese_mask

array([ True,  True, False,  True,  True,  True, False])


# FUNDAMENTALS IN PANDAS
1. Data Structures in pandas 
2. File formats and importing data into pandas
3. Basic inspection of a df
4. Indexing/Slicing of df

In [8]:
# csv, tsv, excel files, data from urls

import pandas as pd

df=pd.read_csv(r"C:\Users\Administrator\Downloads\Sales.csv")
df

Brands          Models         Colors Memory                Storage  \
0     SAMSUNG    GALAXY M31S    Mirage Black   8 GB                 128 GB   
1       Nokia             3.2          Steel   2 GB                  16 GB   
2      realme             C2   Diamond Black   2 GB                    NaN   
3     Infinix          Note 5       Ice Blue   4 GB                  64 GB   
4       Apple      iPhone 11           Black    4GB                  64 GB   
...       ...             ...            ...    ...                    ...   
3109     POCO       M4 Pro 5G      Cool Blue   6 GB                 128 GB   
3110    Nokia             225          Black    NaN  Expandable Upto 32 GB   
3111    Apple      iPhone SE           White   2 GB                 128 GB   
3112    Apple  iPhone 13 Pro            Gold   6 GB                 128 GB   
3113   GIONEE             F9            Blue   3 GB                  32 GB   

     Camera  Rating  Selling Price  Original Price                Mobile  \
0       Yes     4.3          19330           20999  SAMSUNG GALAXY M31S    
1       Yes     3.8          10199           10199             Nokia 3.2   
2       Yes     4.4           6999            7999            realme C2    
3       Yes     4.2          12999           12999        Infinix Note 5   
4       Yes     4.6          49900           49900      Apple iPhone 11    
...     ...     ...            ...             ...                   ...   
3109    Yes     4.4          16999           19999        POCO M4 Pro 5G   
3110    Yes     3.6           3499            3499             Nokia 225   
3111    Yes     4.5          44900           44900      Apple iPhone SE    
3112    Yes     NaN         119900          119900  Apple iPhone 13 Pro    
3113    Yes     4.2           7900            7900            GIONEE F9    

      Discount  discount percentage  
0         1669             7.947998  
1            0             0.000000  
2         1000            12.501563  
3            0             0.000000  
4            0             0.000000  
...        ...                  ...  
3109      3000            15.000750  
3110         0             0.000000  
3111         0             0.000000  
3112         0             0.000000  
3113         0             0.000000  

[3114 rows x 12 columns]

In [9]:
df.shape

(3114, 12)

In [12]:
df.describe()

Rating  Selling Price  Original Price      Discount  \
count  2970.000000    3114.000000     3114.000000   3114.000000   
mean      4.243098   26436.625562    28333.473025   1896.847463   
std       0.271991   30066.892622    31525.599889   5337.126176   
min       2.300000    1000.000000     1000.000000  -8000.000000   
25%       4.100000    9990.000000    10030.250000      0.000000   
50%       4.300000   15000.000000    16889.500000      0.000000   
75%       4.400000   28999.000000    31500.000000   2000.000000   
max       5.000000  179900.000000   189999.000000  75000.000000   

       discount percentage  
count          3114.000000  
mean              6.086788  
std              11.106776  
min            -160.320641  
25%               0.000000  
50%               0.000000  
75%               9.836388  
max              70.610305

In [13]:
df.columns

Index(['Brands', 'Models', 'Colors', 'Memory', 'Storage', 'Camera', 'Rating',
       'Selling Price', 'Original Price', 'Mobile', 'Discount',
       'discount percentage'],
      dtype='object')

In [14]:
df.iloc[0:5, 0:2]

Brands        Models
0  SAMSUNG  GALAXY M31S 
1    Nokia           3.2
2   realme           C2 
3  Infinix        Note 5
4    Apple    iPhone 11

In [18]:
df.iloc[0:10, [0,7,8]]

Brands  Selling Price  Original Price
0  SAMSUNG          19330           20999
1    Nokia          10199           10199
2   realme           6999            7999
3  Infinix          12999           12999
4    Apple          49900           49900
5   GIONEE           2199            2199
6    Apple          99900           99900
7    Apple          42999           47900
8  SAMSUNG          20400           20400
9   Xiaomi          21736           22999

In [21]:
df.iloc[:, 1:6]

Models         Colors Memory                Storage Camera
0       GALAXY M31S    Mirage Black   8 GB                 128 GB    Yes
1                3.2          Steel   2 GB                  16 GB    Yes
2                C2   Diamond Black   2 GB                    NaN    Yes
3             Note 5       Ice Blue   4 GB                  64 GB    Yes
4         iPhone 11           Black    4GB                  64 GB    Yes
...              ...            ...    ...                    ...    ...
3109       M4 Pro 5G      Cool Blue   6 GB                 128 GB    Yes
3110             225          Black    NaN  Expandable Upto 32 GB    Yes
3111      iPhone SE           White   2 GB                 128 GB    Yes
3112  iPhone 13 Pro            Gold   6 GB                 128 GB    Yes
3113             F9            Blue   3 GB                  32 GB    Yes

[3114 rows x 5 columns]

In [ ]:
data={
 'Name': ['Stanley', 'Ruth', 'Berlin', 'Esther'],
 'Grades': [20,30,40,50],
 'Subject': ['English','Math','Geography', 'Computer Science']
 }

df=pd.DataFrame(data,index=['A','B','C','D'])
 




Names  Grades           Subject
A  Stanley      80           English
B   Berlin      60              Math
C      Ivy      70         Geography
D     Ruth      77  Computer Science

In [27]:
df.loc[['C', 'A', 'D']]

Names  Grades           Subject
C      Ivy      70         Geography
A  Stanley      80           English
D     Ruth      77  Computer Science

In [28]:
df.loc[:, 'Grades']

A    80
B    60
C    70
D    77
Name: Grades, dtype: int64

In [ ]:
df.loc[:, ['Grades','Names']]

Grades    Names
A      80  Stanley
B      60   Berlin
C      70      Ivy
D      77     Ruth

In [ ]:
df.loc[['B', 'D'], ['Grades', 'Subject']]

Grades           Subject
B      60              Math
D      77  Computer Science