# Intro to numpy


In [1]:
# Dimensions in arrays
# 0D array-scalar- one numerical value
# 1D array-vector- list of elements
# 2D array-list of elements are the elements
# 3D array- 2D arrays are the elements

In [2]:
# arrays from lists or tuples
# np.array()

import numpy as np

my_list=[1,2,3,4,5]
arr1=np.array(my_list)
arr1

array([1, 2, 3, 4, 5])

In [3]:
my_list=[[1,2,3],[4,5,6]]
arr2=np.array(my_list)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# array from random values

arr3=np.random.rand(5,5)
arr3

array([[0.39073353, 0.01777856, 0.97383265, 0.18523451, 0.04953533],
       [0.84182504, 0.23917894, 0.94891736, 0.00725172, 0.36040096],
       [0.36156429, 0.00415161, 0.50200217, 0.31213639, 0.31611469],
       [0.38771582, 0.30299282, 0.3335306 , 0.27636646, 0.11313346],
       [0.0697844 , 0.67848517, 0.64586974, 0.57376349, 0.43886621]])

In [6]:
arr4=np.random.randint(100, size=(5,5))
print(arr4)

[[56 56 85 19 75]
 [35 95 29 48  0]
 [29 23 48  3 39]
 [ 8 12 34 94 79]
 [92 92 14 52 47]]


In [7]:
arr5=np.full((2,3,4),9)
print(arr5)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]


In [8]:
arr6=np.arange(0,50,2)
arr6

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [12]:
# temperature qtn
# create array to store temps for 5 days and 7 stations
arr7=np.random.randint(15,40, size=(5,7))
arr7

array([[39, 19, 26, 23, 27, 26, 23],
       [31, 24, 32, 28, 16, 35, 25],
       [20, 21, 19, 22, 16, 26, 25],
       [37, 17, 39, 23, 34, 34, 32],
       [28, 19, 27, 17, 17, 21, 20]], dtype=int32)

In [14]:
# initialize an array for 30 students starting at 25
arr8=np.random.randint(25,100, size=(30))
arr8

array([67, 85, 33, 61, 64, 88, 56, 71, 44, 67, 79, 37, 78, 90, 61, 72, 99,
       41, 30, 86, 82, 40, 56, 57, 65, 70, 28, 81, 89, 56], dtype=int32)

In [ ]:
()