#### 1. Import the numpy package under the name `np` (★☆☆)"
#### 2. Print the numpy version and the configuration (★☆☆)
#### 3. Create a null vector of size 10 (★☆☆)

In [8]:
import numpy as np
np.version

arr1=np.array([1,2,3,4,5,6,7,8,9,10])
arr1



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 4. How to find the memory size of any array (★☆☆)

In [9]:
arr1.size

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
arr2=arr1[::-1]
arr2

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
arr3=np.random.randint(8, size=(3,3))
arr3

array([[2, 4, 5],
       [4, 2, 7],
       [2, 2, 4]], dtype=int32)

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
arr4=np.array()