#### 1. Import the numpy package under the name `np` (★☆☆)"
#### 2. Print the numpy version and the configuration (★☆☆)
#### 3. Create a null vector of size 10 (★☆☆)

In [8]:
import numpy as np
np.version

arr1=np.array([1,2,3,4,5,6,7,8,9,10])
arr1



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### 4. How to find the memory size of any array (★☆☆)

In [9]:
arr1.size

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
import numpy as np
np.add

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [2]:
import numpy as np
arr2=np.zeros(10)
arr2[4]=1
print(arr2)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [3]:
import numpy as np
arr3=np.arange(10, 49)
print(arr3)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
arr2=arr1[::-1]
arr2

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
arr3=np.random.randint(8, size=(3,3))
arr3

array([[2, 4, 5],
       [4, 2, 7],
       [2, 2, 4]], dtype=int32)

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [5]:
import numpy as np
arr4=np.array([1,2,0,0,4,0])
non_zero=np.nonzero(arr4)
print(non_zero[0])

[0 1 4]
