# Numpy Exercise 3

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [4]:
import numpy as np


np.sqrt(-1)==np.emath.sqrt(-1)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_18464\3141062399.py:4: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)==np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [5]:
arr1=np.random.randint(4, size=(5,5))
arr1

array([[1, 3, 2, 0, 2],
       [0, 0, 0, 2, 1],
       [3, 1, 2, 0, 0],
       [0, 0, 3, 1, 3],
       [0, 2, 2, 2, 3]], dtype=int32)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [6]:
arr2=np.random.rand(10)
arr2

array([0.50055024, 0.93257888, 0.00178609, 0.75768187, 0.63693285,
       0.85043582, 0.9548978 , 0.40306212, 0.85053153, 0.02309927])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [10]:
arr3=np.array([0,4,6,77,88,78,33,47,56,100])
sortedarr3=np.sort(arr3)
sortedarr3

array([  0,   4,   6,  33,  47,  56,  77,  78,  88, 100])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [11]:
# Use of the sum function
arr4=np.array([1,2,3,4,5])
total=sum(arr4)
total

np.int64(15)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [12]:
A=np.random.randint(100)
B=np.random.randint(100)
A==B

False

#### 43. Make an array immutable (read-only) (★★☆)

In [14]:
arr5=np.array([4,66,77,88,"Stanley"])
immutable_arr5=tuple(arr5)
immutable_arr5

(np.str_('4'), np.str_('66'), np.str_('77'), np.str_('88'), np.str_('Stanley'))

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [27]:
arr6=np.random.randint(10, size=(10))
print(arr6)
arr7=arr6.copy()
arr7[np.argmax(arr6)]=0
arr7

[5 8 7 1 1 0 8 9 7 3]


array([5, 8, 7, 1, 1, 0, 8, 0, 7, 3], dtype=int32)